workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: android
        script: chmod +w ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - abishek.choudhari555@gmail.com