workflows:
  my-workflow:
    scripts: |
      - name: Build Android APK
        working_directory: android
        chmod -R 777 $CM_BUILD_DIR
        cd android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - abishek.choudhari555@gmail.com